Внутренняя  страница на флексах
htmlacademy-htmlcss/1744861-sedona-31 pull request #10
Opened 2021-06-20 17:56 UTC by Proalex90

2021-06-22 04:43 UTC, kondzerau-ivan requested changes

2021-06-22 04:43 UTC, kondzerau-ivan commented on css/style.css
> +.results__leveler:first-child:before {
Нет, так рамки мы делать не станем, потому что для этого нам псевдо-элементы не нужны.
Делаем первому элементу **.results__leveler:first-child** рамку и сверху и снизу, а всем остальным **.results__leveler + .results__leveler** только снизу.

2021-06-22 04:43 UTC, kondzerau-ivan commented on css/style.css
> +  margin: 27px 73px;
Это не правильный подход.
Если тебе надо сделать отступы с внешним блоком, то делай это через родителя и паддинги.

2021-06-22 04:43 UTC, kondzerau-ivan commented on css/style.css
> +  margin-top: auto;
**margin-top: auto;**
Зачем?

2021-06-22 04:43 UTC, kondzerau-ivan commented on css/style.css
> +  display: block;
Параграф - это уже блочный элемент.

2021-06-22 04:43 UTC, kondzerau-ivan commented on css/style.css
> +  padding-top: 3px;
Зачем? Чтобы текст отцентрировать? Так лучше в таком случае это делать через line-height.

2021-06-22 04:43 UTC, kondzerau-ivan commented on css/style.css
> +  right: 0;
Зачем?

2021-06-22 04:43 UTC, kondzerau-ivan commented on css/style.css
> +  top: 0;
Зачем?

2021-06-22 04:43 UTC, kondzerau-ivan commented on css/style.css
> +  position: relative;
Зачем?

2021-06-22 04:43 UTC, kondzerau-ivan commented on css/style.css
> +  margin: 0 73px 0;
Нет, делать внешние отступы через внешний блок (контейнер) и паддинги.

2021-06-22 04:43 UTC, kondzerau-ivan commented on css/style.css
>    justify-content: flex-start;
Это значение по дефолту, зачем его прописывать?

2021-06-22 04:43 UTC, kondzerau-ivan commented on css/style.css
>  /* FLEX */
Какую информацию несёт этот комментарий?

2021-06-22 04:43 UTC, kondzerau-ivan commented on css/style.css
> +  margin: 30px 73px;
См. комменты выше.

2021-06-22 04:43 UTC, kondzerau-ivan commented on css/style.css
>  .filter__form legend {
У нас есть классы для селекторов.

2021-06-22 04:43 UTC, kondzerau-ivan commented on css/style.css
>  .filter__form {
![2021-06-22_07-39](https://user-images.githubusercontent.com/24848155/122864493-6798fa80-d32d-11eb-8ad4-e139ad2d4faa.png)
Что это за пустое пространство?
У тебя филдсеты выпадают из формы.

2021-06-23 12:57 UTC, Proalex90 commented on css/style.css
> +  margin-top: auto;
Что бы выровнять верхушку изображения и заголовок h4 что бы начинались с одной линии (согласно макету)

2021-06-23 16:38 UTC, Proalex90 commented on css/style.css
> +  position: relative;
Устаревшие данные, забыл удалить

2021-06-23 16:59 UTC, Proalex90 commented on css/style.css
>  .filter__form legend {
А зачем мне писать 3 строчки указывая каждый селектор когда можно заменить один словом? (у меня у каждой легенды свой класс)

2021-06-24 09:39 UTC, merged